server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: service-vod     # 服务名
  servlet:
    multipart:
      max-file-size: 1024MB    # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # nacos服务地址
aliyun:
  vod:
    file:
      accessKeyId:
      accessKeySecret:
