server:
  port: 8005             # 服务端口
spring:
  application:
    name: service-msm    # 微服务名称
  profiles:
    active: dev          # 设置为开发环境
  jackson:                            # 配置json全局时间
    date-format: yyyy-MM-dd HH:mm:ss  # 配置返回json的时间格式
    time-zone: GMT+8                  # json是格林尼治时间，和我们相差8小时，需要加上8
  redis:
    host:                             # ip地址
    port: 6379                        # 端口号
    database: 0
    timeout: 1800000                  # 超时时间
    lettuce:
      pool:
        max-active: 20
        max-wait: -1                  # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0                   # 最小空闲
mybatis-plus:                         # mybatis-plus日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml
tencent:
  msm:
    secretID:                             # keyId
    secretKey:                            # secreKey
    endPoint:
    appId:                                # 短信的应用号
    signName:                             # 签名
    templateId:                           # 模板id

