server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # nacos服务地址
aliyun:
  oss:
    file:
      endpoint:
      bucketName:
      accessKeyId:
      accessKeySecret:
